exports.LOADING_BLOG = "LOADING_BLOG";
exports.LOADED_BLOG = "LOADED_BLOG";
exports.LOAD_BLOG = "LOAD_BLOG";
exports.ADD_BLOG = "ADD_BLOG";
exports.DELETE_BLOG = "DELETE_BLOG";
exports.UPDATE_BLOG = "UPDATE_BLOG";
exports.GET_SINGLE_BLOG = "GET_SINGLE_BLOG";
